package com.example.backend.contract;

public enum ContractAction {
    SUBMIT_SUPPLIER_CONFIRM,
    SUPPLIER_CONFIRMED,
    SUBMIT_APPROVAL,
    CANCEL_PROCESS,
    WITHDRAW_APPROVAL,
    APPROVE,
    REJECT,
    START_EXECUTION,
    REGISTER_PAYMENT,
    REGISTER_ACCEPTANCE,
    COMPLETE,
    ARCHIVE,
    REQUEST_TERMINATION,
    APPROVE_TERMINATION,
    REJECT_TERMINATION,
    TERMINATE
}
